name: Build

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  canary:
    name: Canary

    if: startsWith(github.event.head_commit.message, 'chore(release)') == false

    permissions:
      id-token: write # to create releae with provenance

    runs-on: ubuntu-latest

    steps:
      - name: Publish canary release
        run: pnpm run release:canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true

  production:
    name: Production

    if: startsWith(github.event.head_commit.message, 'chore(release)') == true

    permissions:
      id-token: write # to create releae with provenance

    runs-on: ubuntu-latest

    steps:
      - name: Publish release
        run: pnpm publish --filter @vuetils/form --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
